#!/bin/sh

printf "power
hdmi-1
hdmi-2
vol+
vol-
mute
source
channel+
channel-
last
menu
info
add
exit
manual
tools
guide
back
up
down
left
right
enter
channels
smart-hub
hdmi-3
hdmi-4
0
1
2
3
4
5
6
7
8
9
" | dmenu -p "Commands:" $@ | \
    while read -r selection; do \
        if [ -n "$selection" ]; then
            if [ "$selection" = "vol+" ] || [ "$selection" = "vol-" ]; then
                printf "1\n5\n10\n15\n20\n" | dmenu -p "vol up" $@ | \
                    while read -r volume; do
                        for index in $(seq $volume); do
                            curl -X POST "http://$TV_MODULE_IP/ir/$selection"
                            echo "$index"
                            sleep 0.1
                        done
                    done
            else
                curl -X POST "http://$TV_MODULE_IP/ir/$selection"
            fi

        fi
    done
