#!/bin/sh

#This file is part of the Calebe94 Scripts distribution (https://git.calebe.dev.br/scripts).
#Copyright (C) 2021 Edimar Calebe Castanho
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

[ -z $(which wmctrl) ] && echo '"wmctrl" not found.' && exit 1

arguments="$@"

wmctrl -l | awk '{$1=$2=$3=""; print }' | cut -c 4- | dmenu $@ | \
{ read client; [ -n "$client" ] && wmctrl -a "$client" && exit 0 || echo "No client selected!"; exit 1; }
