#!/bin/sh

#This file is part of the Calebe94 Scripts distribution (https://git.calebe.dev.br/scripts).
#Copyright (C) 2021 Edimar Calebe Castanho
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

[ -z "$(which wmctrl)" ] && echo '"wmctrl" not found.' && exit 1

activate_window()
{
    client="$1"
    client_name="$(echo "$client" | awk '$1=""; {print}' | cut -c 2-)"
    client_pid="$(echo "$client" | awk '{print $1}')"
    client_pid_scratchpad=$(grep "$client_pid" /tmp/dwm_scratchpad 2> /dev/null | awk '{print $1}')

    # Check if client is in scratchpad
    # If it is, send a signal to dwm (depends on dwmc patch)
    # If it is not use wmctrl
    if [ -z "$client_pid_scratchpad" ]; then
        wmctrl -a "$client_name"
    else
        xsetroot -name "fsignal:scratchpad_show v $client_pid"
    fi
}

list_windows()
{
    wmctrl -l | awk '$3=$2=""; {print}'
    [ -n "$TMENU_FILE" ] && tmenu
}

list_windows | dmenu $* | \
{ read -r client; [ -n "$client" ] && activate_window "$client" && exit 0 || echo "No client selected!"; exit 1; }
